# Generated by Django 3.1.6 on 2021-05-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45, null=True)),
                ('phone_number', models.CharField(max_length=45, null=True)),
                ('discription', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45, null=True)),
                ('phone_number', models.CharField(max_length=45, null=True)),
                ('discription', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
