# Generated by Django 3.1.6 on 2021-05-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='website',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
