# Generated by Django 3.1.6 on 2021-05-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation_Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('flag', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('unit_cost', models.IntegerField(default=10000)),
                ('selling_price', models.IntegerField(default=10000, null=True)),
                ('origin', models.CharField(max_length=45)),
                ('calculationUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.calculation_unit')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Product.typeproduct')),
            ],
            options={
                'ordering': ['type_product__name'],
            },
        ),
    ]
